export const USER_LOGIN = 'USER_LOGIN';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const ANALYZE_ITEMS = 'ANALYZE_ITEMS';
export const ANALYZE_LOADING = 'ANALYZE_LOADING';
export const COMREHENSION_ITEMS = 'COMREHENSION_ITEMS';
export const COMREHENSION_LOADING = 'COMREHENSION_LOADING';